plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.chaquo.python'
}

android {
    namespace 'com.chaquo.python.console'
    compileSdk = 34
    defaultConfig {
        applicationId "com.chaquo.python.console"
        minSdk = 24
        targetSdk = 34
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        ndk {
            abiFilters "arm64-v8a", "x86_64"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

chaquopy {
    defaultConfig {
        buildPython "/opt/homebrew/Caskroom/miniconda/base/envs/doan_py310/bin/python"

        version "3.10"

        pip {
            install "pandas"
            install "scikit-learn"
            install "scipy"
            install "numpy"
            install "six"
            install "opencv-python-headless"
            install "certifi"
            install "requests"
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.1.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.activity:activity:1.9.3'
    implementation 'androidx.core:core-ktx:1.13.1'

    // Google & Firebase
    implementation platform('com.google.firebase:firebase-bom:34.12.0')
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'com.google.firebase:firebase-storage'

    implementation 'com.google.android.gms:play-services-auth:20.7.0'

    implementation 'com.github.bumptech.glide:glide:4.16.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.16.0'

    implementation 'com.google.code.gson:gson:2.14.0'

    testImplementation 'androidx.arch.core:core-testing:2.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0'
}

tasks.register("testClasses") {
    dependsOn "compileDebugUnitTestSources"
}

apply plugin: 'com.google.gms.google-services'
